name: Build & Deploy to Kind

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/backend
  FRONTEND_IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/frontend
  TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend image
        run: |
          docker build -t $BACKEND_IMAGE:$TAG ./backend

      - name: Build Frontend image
        run: |
          docker build -t $FRONTEND_IMAGE:$TAG ./frontend

      - name: Push Backend image
        run: docker push $BACKEND_IMAGE:$TAG

      - name: Push Frontend image
        run: docker push $FRONTEND_IMAGE:$TAG

      - name: Setup kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0

      # ---------------- BACKEND DEPLOY ----------------
      - name: Apply Backend Deployment
        run: |
          echo "---- Applying Backend Deployment ----"
          kubectl apply -f k8s/backend-deployment.yaml
          
          echo "---- Current backend pods ----"
          kubectl get pods -l app=backend -o wide

          echo "---- Backend pod events (image pull etc.) ----"
          kubectl describe pod -l app=backend || true

          echo "---- Backend deployment image ----"
          kubectl get deployment backend-deployment -o yaml | grep "image:" || true

      # ---------------- FRONTEND DEPLOY ----------------
      - name: Apply Frontend Deployment
        run: |
          echo "---- Applying Frontend Deployment ----"
          kubectl apply -f k8s/frontend-deployment.yaml
          
          echo "---- Current frontend pods ----"
          kubectl get pods -l app=frontend -o wide

          echo "---- Frontend pod events (image pull etc.) ----"
          kubectl describe pod -l app=frontend || true

          echo "---- Frontend deployment image ----"
          kubectl get deployment frontend-deployment -o yaml | grep "image:" || true

      # ---------------- WAIT FOR PODS ----------------
      - name: Wait for pods to be ready
        run: |
          echo "Waiting for backend pod to be ready..."
          kubectl wait --for=condition=ready pod -l app=backend --timeout=120s || true

          echo "Waiting for frontend pod to be ready..."
          kubectl wait --for=condition=ready pod -l app=frontend --timeout=120s || true

      # ---------------- FINAL DEBUG ----------------
      - name: Final debug if pods not ready
        run: |
          echo "---- ALL DEPLOYMENTS ----"
          kubectl get deployments -o wide

          echo "---- ALL PODS ----"
          kubectl get pods -o wide

          echo "---- Backend pod describe ----"
          kubectl describe pod -l app=backend || true

          echo "---- Frontend pod describe ----"
          kubectl describe pod -l app=frontend || true
